language: java
env:
- USER_LANGUAGE=en USER_REGION=US'
os:
- linux
jdk:
- openjdk11
install:
- mvn clean install
cache:
  directories:
  - "$HOME/.m2"
after_success:
- mkdir $TRAVIS_BUILD_DIR/out
- mv $TRAVIS_BUILD_DIR/target/*.jar $TRAVIS_BUILD_DIR/out
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAIIFP4UJHTPNSKSMQ
  secret_access_key:
    secure: KHTO8gvudK2zh8/CtRgcDep/BEw25F4MwPQ9SMOQGU7x3mkBxKVs+68dg6mem8mT+4wxUDDPIeB89fUtF8nzK8dQkH5QQ+oLzH0t1gn35Hb8XJKBn2W4Yy5xS2JxkoRZGK5vZY8PBl1glhAkLb0ehJsgH0bSco66wg7Duqf2zC4kJ3HCqrD4mQ4ZUssLG9Wucf+XxALnmlD2hjjKKnR0ekk9gUwQ2UXHoespCqfCAQjdvXQn5YZOter6vr8MU/s1RlKEJv9qTXAVMK8jCZvn3wduQg5f6m1+lpn+vbeNm3bLYSSBfFb9qtzTLwPHEm4wCEEHd/GZHC75vOCVKuI1aiPasniGBGrqBj+fC2dXYkqru+47ZeLhrCrvGH+7eF0ljWs0fwFj1SpNhcX5Kr/ii6Z50N+hCVB7rbjryCeJMVsLmkThhYxfImrDLrN11tM2SgAI/jIIpIiQwm27QjWT7jb+4ZYktmkT81yZEDW5mff43rkfWKawOOM/wuKLcMB8ERd6NP7lq2S13j/m510InH/7izMGS+kSnhD86tMMN1BCdTMVF4K4KS7SaFh1Qj/vCp8oiXiLCSoPjIoYEe5/TAoOvHGsoTgsTC1LJIBdUDngWMZ5VLUQ/0b5qYrEIxDwHlJE+JExKIzr3SVkgtlLlEQXOvnL7ogW3VQ/asGS58U=
  bucket: hm-witsml-server
  local-dir: "$TRAVIS_BUILD_DIR/out"
  acl: public_read
  on:
    repo: hashmapinc/DrillTest
